-- Supabase / PostgreSQL schema for Smart Admission Management System
-- Run this in the Supabase SQL editor for your project.

-- Create enum types for choices if desired (optional); here we'll use text with constraints

CREATE TABLE IF NOT EXISTS students (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  date_of_birth date NOT NULL,
  gender text NOT NULL CHECK (gender IN ('Male','Female','Other')),
  category text NOT NULL CHECK (category IN ('General','OBC','SC','ST')),
  aadhaar_number varchar(12) NOT NULL UNIQUE,
  nationality text NOT NULL,
  email text NOT NULL UNIQUE,
  mobile_number varchar(15) NOT NULL,
  complete_address text NOT NULL,
  parent_name text NOT NULL,
  parent_occupation text NOT NULL,
  parent_contact varchar(15) NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id bigint NOT NULL REFERENCES students(id) ON DELETE CASCADE,
  tenth_marks numeric(5,2) NOT NULL,
  tenth_board text NOT NULL,
  tenth_year integer NOT NULL,
  twelfth_marks numeric(5,2) NOT NULL,
  twelfth_board text NOT NULL,
  twelfth_year integer NOT NULL,
  entrance_exam_name text NOT NULL,
  entrance_rank numeric(7,2) NOT NULL,
  primary_choice text NOT NULL CHECK (primary_choice IN ('Computer Science','Information Technology','Mechanical','Civil','Electrical','Electronics')),
  secondary_choice text NOT NULL CHECK (secondary_choice IN ('Computer Science','Information Technology','Mechanical','Civil','Electrical','Electronics')),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS documents (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  application_id bigint NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  photo_path text,
  signature_path text,
  tenth_marksheet_path text,
  twelfth_marksheet_path text,
  entrance_certificate_path text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS streams (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE
);

-- Seed streams
INSERT INTO streams (name)
SELECT v FROM (VALUES
  ('Computer Science'),
  ('Information Technology'),
  ('Mechanical'),
  ('Civil'),
  ('Electrical'),
  ('Electronics')
) AS x(v)
ON CONFLICT (name) DO NOTHING;

-- Note: Create a storage bucket named 'uploads' in the Supabase dashboard > Storage
-- Set the bucket to public if you want direct public URLs; otherwise use signed URLs.
